### ISSUE TITLE
Seed and Source Files

### ISSUE THREAD

**Issue by apassenger** [michelemancusi/libtrevisan#1]
Hello,

Source file is produced our state measurement right? If it is not, after measuring the state what should we do for producing source file?

And regarding the seed file, this is produced by min entropy of our source file right?

Can you explain a bit how can we produced seed file?

Best regards

**Comment by michelemancusi** [comment]
Yes, the source file is produced by your state measurements and the seed is a uniform random seed for example produced by a classical computer.
