### ISSUE TITLE
Problem of compilation with GNU gcc compilers

### ISSUE THREAD

**Issue by Adarshsingh2203** [michelemancusi/libtrevisan#2]
Compiling with GNU compiler (gcc) is presenting with a lot of errors which include typecasting, data type not found and MACRO undeclared/ re-declared.

**Comment by Adarshsingh2203** [comment]
I want to work on this issue @michelemancusi

**Comment by michelemancusi** [comment]
It has been a long time and surely the libraries have changed. If you have the will and time to work on it I would appreciate it.

**Comment by Adarshsingh2203** [comment]
Cool, I would like to work on this

**Comment by michelemancusi** [comment]
Please, feel free
